MESSAGE(STATUS "Include Download.cmake")

FUNCTION(DOWNLOAD_FILE URL FILE_NAME HASH_TYPE HASH)
    IF (EXISTS ${FILE_NAME})
        FILE(${HASH_TYPE} ${FILE_NAME} ORIGIN_FILE_HASH)
        STRING(TOLOWER ${HASH} LHASH)
        STRING(TOLOWER ${ORIGIN_FILE_HASH} LORIGIN_FILE_HASH)
        IF (${LHASH} STREQUAL ${LORIGIN_FILE_HASH})
            MESSAGE(STATUS "Found file: ${FILE_NAME} with same ${HASH_TYPE}")
            RETURN()
        ELSE ()
            MESSAGE(STATUS "Found file: ${FILE_NAME} with different ${HASH_TYPE}")
        ENDIF ()
    ENDIF ()
    MESSAGE(STATUS "Download file: ${FILE_NAME}")
    FILE(DOWNLOAD ${URL} ${FILE_NAME}
            TIMEOUT 60 # seconds
            EXPECTED_HASH ${HASH_TYPE}=${HASH}
            TLS_VERIFY ON)
ENDFUNCTION()

FUNCTION(DOWNLOAD_TEST_FILE URL FILE_NAME HASH_TYPE HASH)
    IF ("${BUILD_TEST}" STREQUAL "OFF" OR "${BUILD_TEST}" STREQUAL "")
        RETURN()
    ENDIF ()
    DOWNLOAD_FILE(${URL} ${FILE_NAME} ${HASH_TYPE} ${HASH})
ENDFUNCTION()