# 1. include all cmake files
# 2. debug postfix
# 3. C++ 17
# 4. install prefix
# 5. set BUILD_TEST_${PROJECT_NAME}
# 6. output directory
# 7. use folder

MESSAGE(STATUS "Include Init.cmake")

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Basic.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Build.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Download.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Git.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Package.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/Qt.cmake")

# ---------------------------------------------------------

MACRO(INIT_PROJECT)
    SET(CMAKE_DEBUG_POSTFIX d)

    SET(CMAKE_CXX_STANDARD 17)
    SET(CMAKE_CXX_STANDARD_REQUIRED True)

    IF (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
        PATH_BACK(ROOT ${CMAKE_INSTALL_PREFIX} 1)
        SET(CMAKE_INSTALL_PREFIX "${ROOT}/My" CACHE PATH "install prefix" FORCE)
    ENDIF ()

    SET("BUILD_TEST_${PROJECT_NAME}" TRUE CACHE BOOL "Build tests for ${PROJECT_NAME} ")

    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin")
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/bin")
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/bin")
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/lib")
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/lib")
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/lib")
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/lib")
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/lib")
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/lib")

    SET_PROPERTY(GLOBAL PROPERTY USE_FOLDERS ON)
ENDMACRO()