# [ Interface ]
#
# GET_DIR_NAME(<RESULT_NAME>)
# - Get current directory name.
#
# ADD_SUB_DIRS()
# - Add all subdirectories.
#
# ADD_CURRENT_PATH_SRCS(<RESULT_NAME>)
# - Add all source files in the current directory.
#
# LIST_CHANGE_SEPARATOR(RST <RESULT_NAME> SEPARATOR <SEPARATOR> LIST <LIST>)
# - Separator '/': "a;b;c" -> "a/b/c"
#
# ADD_TARGET_GDR(MODE <MODE> NAME <NAME> SOURCES <SOURCES_LIST> LIBS_GENERAL <LIBS_GENERAL_LIST> LIBS_DEBUG <LIBS_DEBUG_LIST> LIBS_RELEASE <LIBS_RELEASE_LIST>)
# - Mode: EXE, LIB, DLL
# - LIBS_GENERAL_LIST: auto add debug prefix in debug mode
# - Auto set the folder, target prefix and some properties.
#
# ADD_TARGET(MODE <MODE> NAME <NAME> SOURCES <SOURCES_LIST> LIBS <LIBS_LIST>)
# - Call ADD_TARGET_GDR with LIBS_DEBUG and LIBS_RELEASE empty.
#
# QT_BEGIN()
# - Call it before adding Qt target.
#
# QT_END()
# - Call it after adding Qt target.

FUNCTION(GET_DIR_NAME DIR_NAME)
    STRING(REGEX MATCH "([^/]*)$" TMP ${CMAKE_CURRENT_SOURCE_DIR})
    SET(${DIR_NAME} ${TMP} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(ADD_SUB_DIRS)
    FILE(GLOB CHILDREN RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/*)
    SET(DIR_LIST "")
    FOREACH (CHILD ${CHILDREN})
        IF (IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${CHILD})
            LIST(APPEND DIR_LIST ${CHILD})
        ENDIF ()
    ENDFOREACH ()
    GET_DIR_NAME(DIR_NAME)
    LIST(APPEND FOLDERS ${DIR_NAME})
    FOREACH (DIR ${DIR_LIST})
        ADD_SUBDIRECTORY(${DIR})
    ENDFOREACH ()
ENDFUNCTION()

FUNCTION(ADD_CURRENT_PATH_SRCS RST)
    FILE(GLOB SOURCES
            "${CMAKE_CURRENT_SOURCE_DIR}/*.cxx"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.hxx"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.inl"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.c"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.cc"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.cxx"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.ipp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.tpp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.txx"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.ixx"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.m"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.mm"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.rc"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.rc2"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.def"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.odl"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.idl"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.ui"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qrc"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qss"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qsf"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qif"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qhp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qhp"
            "${CMAKE_CURRENT_SOURCE_DIR}/*.qch"
    )
    SET(${RST} ${SOURCES} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(LIST_CHANGE_SEPARATOR)
    CMAKE_PARSE_ARGUMENTS("ARG" "" "RST;SEPARATOR" "LIST" ${ARGN})
    LIST(LENGTH ARG_LIST LIST_LENGTH)
    IF ($<BOOL:${LIST_LENGTH}>)
        SET(${ARG_RST} "" PARENT_SCOPE)
    ELSE ()
        LIST(POP_BACK ARG_LIST BACK)
        FOREACH (ITEM ${ARG_LIST})
            SET(RST "${RST}${ITEM}${ARG_SEPARATOR}")
        ENDFOREACH ()
        SET(${ARG_RST} "${RST}${BACK}" PARENT_SCOPE)
    ENDIF ()
ENDFUNCTION()

FUNCTION(ADD_TARGET_GDR)
    CMAKE_PARSE_ARGUMENTS("ARG" "" "MODE;NAME" "SOURCES;LIBS_GENERAL;LIBS_DEBUG;LIBS_RELEASE" ${ARGN})

    LIST_CHANGE_SEPARATOR(RST FOLDER_PREFIX SEPARATOR "_" LIST ${FOLDERS})
    LIST_CHANGE_SEPARATOR(RST FOLDER_PATH SEPARATOR "/" LIST ${FOLDERS})
    SET(TARGET_NAME "${PROJECT_NAME}_${FOLDER_PREFIX}_${ARG_NAME}")

    MESSAGE(STATUS "--------------------------------------------------")

    MESSAGE(STATUS "- NAME: ${TARGET_NAME}")
    MESSAGE(STATUS "- FOLDER: ${FOLDER_PATH}")
    MESSAGE(STATUS "- MODE: ${ARG_MODE}")
    MESSAGE(STATUS "- SOURCES:")
    FOREACH (SOURCE ${ARG_SOURCES})
        MESSAGE(STATUS "  - ${SOURCE}")
    ENDFOREACH ()
    MESSAGE(STATUS "- LIBRARIES:")
    MESSAGE(STATUS "  - GENERAL:")
    FOREACH (LIBRARY ${ARG_LIBS_GENERAL})
        MESSAGE(STATUS "    - ${LIBRARY}")
    ENDFOREACH ()
    MESSAGE(STATUS "  - DEBUG:")
    FOREACH (LIBRARY ${ARG_LIBS_DEBUG})
        MESSAGE(STATUS "    - ${LIBRARY}")
    ENDFOREACH ()
    MESSAGE(STATUS "  - RELEASE:")
    FOREACH (LIBRARY ${ARG_LIBS_RELEASE})
        MESSAGE(STATUS "    - ${LIBRARY}")
    ENDFOREACH ()

    IF (SOURCE_NUM EQUAL 0)
        MESSAGE(WARNING "Target [${TARGET_NAME}] has no source files.")
        RETURN()
    ENDIF ()

    # Add target
    IF (${ARG_MODE} STREQUAL "EXE")
        ADD_EXECUTABLE(${TARGET_NAME} ${ARG_SOURCES})
        IF (MSVC)
            SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/bin")
        ENDIF ()
        SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX})
    ELSEIF (${ARG_MODE} STREQUAL "LIB")
        ADD_LIBRARY(${TARGET_NAME} ${ARG_SOURCES})
    ELSEIF (${ARG_MODE} STREQUAL "DLL")
        ADD_LIBRARY(${TARGET_NAME} SHARED ${ARG_SOURCES})
    ELSE ()
        MESSAGE(FATAL_ERROR "Unknown mode: ${ARG_MODE}")
        RETURN()
    ENDIF ()

    # Set folder
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES FOLDER ${FOLDER_PATH})

    FOREACH (LIBRARY ${ARG_LIBS_GENERAL})
        TARGET_LINK_LIBRARIES(${TARGET_NAME} GENERAL ${LIBRARY})
    ENDFOREACH ()
    FOREACH (LIBRARY ${ARG_LIBS_DEBUG})
        TARGET_LINK_LIBRARIES(${TARGET_NAME} DEBUG ${LIBRARY})
    ENDFOREACH ()
    FOREACH (LIBRARY ${ARG_LIBS_RELEASE})
        TARGET_LINK_LIBRARIES(${TARGET_NAME} OPTIMIZED ${LIBRARY})
    ENDFOREACH ()
    INSTALL(TARGETS ${TARGET_NAME}
            RUNTIME DESTINATION bin
            LIBRARY DESTINATION lib
            ARCHIVE DESTINATION lib
    )

    MESSAGE(STATUS "--------------------------------------------------")
ENDFUNCTION()

FUNCTION(ADD_TARGET)
    CMAKE_PARSE_ARGUMENTS("ARG" "" "MODE;NAME" "SOURCES;LIBS" ${ARGN})
    ADD_TARGET_GDR(MODE ${ARG_MODE} NAME ${ARG_NAME} SOURCES ${ARG_SOURCES} LIBS_GENERAL ${ARG_LIBS} LIBS_DEBUG "" LIBS_RELEASE "")
ENDFUNCTION()

FUNCTION(QT_BEGIN)
    SET(CMAKE_AUTOMOC ON PARENT_SCOPE)
    set(CMAKE_AUTOUIC ON PARENT_SCOPE)
    set(CMAKE_AUTORCC ON PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(QT_END)
    SET(CMAKE_AUTOMOC OFF PARENT_SCOPE)
    set(CMAKE_AUTOUIC OFF PARENT_SCOPE)
    set(CMAKE_AUTORCC OFF PARENT_SCOPE)
ENDFUNCTION()
